on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    name: My job
    container:
      image: registry.opensuse.org/home/oorlov/containers/containers/tumbleweed:openqa-tests-ci
    steps:
      - name: Get job status
        run: openqa-cli api --host http://openqa.opensuse.org --apikey=$API_KEY --apisecret=$API_SECRET jobs/1959258