on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    name: My job
    container:
      image: registry.opensuse.org/home/oorlov/containers/containers/tumbleweed:openqa-tests-ci
    steps:
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"