on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    name: My job
    container:
      image: registry.opensuse.org/home/oorlov/containers/containers/tumbleweed:openqa-tests-ci
    steps:
      - name: Get job status
        shell: bash
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          OPENQA_CLIENT_PARAMS: "--host http://openqa.opensuse.org --apikey=$API_KEY --apisecret=$API_SECRET"
          yaml_file: Job_Group_settings.yaml
        run: |
          - openqa-cli api $OPENQA_CLIENT_PARAMS jobs/1959258
