on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    name: My job
    container:
      image: registry.opensuse.org/home/oorlov/containers/containers/tumbleweed:openqa-tests-ci
    steps:
      - uses: actions/checkout@v1
      - name: Deploy Job Group settings
        shell: bash
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
        run: |
          openqa-cli api -X POST --o3 --apikey=$API_KEY --apisecret=$API_SECRET job_templates_scheduling/74 schema=JobTemplates-01.yaml schema=JobTemplates-01.yaml preview=0 --param-file template=Job_Group_settings.yaml